---
- name: Ansible Experiment
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    aws_region: eu-central-1
    ami_id: ami-4354ce2c #CoreOS-stable-1632.2.1-hvm
  roles:
    - vpc
    - ec2        