---
- name: Create a VPC
  ec2_vpc_net:
    state: present
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ aws_region }}"
    tags:
      Name: "{{ vpc_name }}"
      Createdby: ansible
  register: vpc    

# - debug:
#     msg: "{{ vpc }}"

# - meta: end_play
# - fail:

- name: Create public subnet
  ec2_vpc_subnet:
    state: present
    # az: "{{ az }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ subnet_cidr }}"
    tags:
      Name: ansible_public_subnet
      Createdby: ansible
  register: public_subnet

- name: Create Internet gateway
  ec2_vpc_igw:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    # tags:
    #   name: ansible_igw
    #   createdby: Ansible  
  register: igw

- name: Set up public subnet route table
  ec2_vpc_route_table:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    tags:
      Name: ansible_public_rt
      Createdby: ansible
    subnets:
      - "{{ public_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  register: public_route_table

- debug: msg="VPC {{ vpc.vpc.id }} Created in {{ aws_region }}"

