---
# tasks file for ec2
- name: Remove Key Pair
  ec2_key:
    name: "{{ ec2_aws_key_name }}"
    state: absent
    region: "{{ aws_region }}"

- name: Remove private key
  file:
    state: absent
    path: "./{{ ec2_aws_key_name }}"

- name: Get ec2 facts
  ec2_remote_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ ec2_instance_name }}"
  register: ec2

## Method for Ansible 2.4
# - name: Get ec2 facts
#   ec2_instance_facts:
#     region: "{{ aws_region }}"
#   filters:
#     "tag:Name": "{{ ec2_instance_name }}"
#   register: ec2    

- name: Terminate instance
  ec2:
    region: "{{ aws_region }}"
    state: absent
    instance_ids: "{{ item.id }}"
    wait: yes
  with_items: "{{ ec2.instances }}"    